### ISSUE TITLE
on submitting signup form submit button crosses the form

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#46]
![signup](https://user-images.githubusercontent.com/33982495/51430958-40174280-1c48-11e9-8ae5-7c81b85a32a5.PNG)

**Comment by thesmallstar** [comment]
When I made the last PR I tested and it was fine, 
![xxs](https://user-images.githubusercontent.com/42006277/51431324-54aa0980-1c4d-11e9-9bd5-d1209d3f2a69.png)

What might be the problem?

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
Can I work on this?

**Comment by Archies11** [comment]
No, made multiple tries at different locations of code but wasnt sure if I was going right since my gh-pages link is not generating the edits I have made and instead just shows the readme file.

**Comment by thesmallstar** [comment]
@Archies11  I have added the feedback texts and the way they have been added, you need to change the box size. You should find the css in the same file, just increase the height by 20-30 px more. Also, github pages wont work here since a backend is involved you need to set it up using Xammp or any equivalents soft. Reach out for help if you need any :)

**Comment by prateek76** [comment]
@Archies11 any progress?
